server:
  port: 8080

spring:
  application:
    name: "uaap-data-scraper"
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always      #for initialization of schema.sql
  main:
    allow-bean-definition-overriding: true

image:
  source: "/uaap-games/images/"

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG

