server:
  port: 8080

spring:
  application:
    name: "uuapdata-service"
  datasource:
    url: jdbc:h2:mem:uaap_data
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG


#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PASSWORD}
#
##spring.datasource.url=jdbc:mysql://localhost:3306/testv2
##spring.datasource.username=springstudent
##spring.datasource.password=springstudent
##spring.main.banner-mode=off
#
#spring.main.allow-bean-definition-overriding=true
#spring.jpa.hibernate.ddl-auto=none
#
#server.port=${SERVER_PORT}
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.web = DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE